### ISSUE TITLE
bnerin cok

### ISSUE THREAD

**Issue by hanzBT** [Urbaeexyz/whatsapp-bot2#23]
case prefix+'play':
            if(isReg(obj)) return
            if(cekumur(cekage)) return
            if (!isPremium) return await hanz.reply(from, `Nomor kamu belum terdaftar sebagai user premium. Hubungi owner untuk mendaftar!`, id)
            if (!isGroupMsg) return hanz.reply(from, 'Perintah ini hanya bisa di gunakan dalam group', id)
            if (isLimit(serial)) return hanz.reply(from, `Maaf ${pushname}, Kuota Limit Kamu Sudah Habis, Ketik #ceklimit Untuk Mengecek Kuota Limit Kamu`, id)
            if (args.length == 1) return hanz.reply(from, `Untuk mencari lagu dari youtube\n\nPenggunaan: #play judul lagu`, id)
            try {
                hanz.reply(from, mess.wait, id)
                const serplay = body.slice(6)
                const webplay = await fetch(`https://api.vhtear.com/ytmp3?query=${serplay}&apikey=${vhtearkey}`)
                if (!webplay.ok) throw new Error(`Error Play : ${webplay.statusText}`)
                const webplay2 = await webplay.json()
                 if (webplay2.status == false) {
                    hanz.reply(from, `*Maaf Terdapat kesalahan saat mengambil data, mohon pilih media lain...*`, id)
                } else {
                    if (Number(webplay2.result.size.split(' MB')[0]) >= 10.00) return hanz.reply(from, 'Maaf durasi music sudah melebihi batas maksimal 10 MB!', id)
                    const { image, mp3, size, ext, title, duration } = await webplay2.result
                    const captplay = `*「 PLAY 」*\n\n• *Judul* : ${title}\n• *Durasi* : ${duration}\n• *Filesize* : ${size}\n• *Exp* : ${ext}\n\n_*Music Sedang Dikirim*_`
                    hanz.sendFileFromUrl(from, image, `thumb.jpg`, captplay, id)
                    await hanz.sendFileFromUrl(from, mp3, `${title}.mp3`, '', id).catch(() => hanz.reply(from, mess.error.Yt4, id))
                    await limitAdd(serial)
                }
            } catch (err) {
                hanz.sendText(ownerNumber, 'Error Play : '+ err)
                hanz.reply(from, 'Jangan meminta lagu yang sama dengan sebelumnya!', id)
            }
            break

**Comment by Urbaeexyz** [comment]
```
case prefix+'play':
if(isReg(obj)) return
if(cekumur(cekage)) return
if (!isPremium) return await hanz.reply(from, Nomor kamu belum terdaftar sebagai user premium. Hubungi owner untuk mendaftar!, id)
if (!isGroupMsg) return hanz.reply(from, 'Perintah ini hanya bisa di gunakan dalam group', id)
if (isLimit(serial)) return hanz.reply(from, Maaf ${pushname}, Kuota Limit Kamu Sudah Habis, Ketik #ceklimit Untuk Mengecek Kuota Limit Kamu, id)
if (args.length == 1) return hanz.reply(from, Untuk mencari lagu dari youtube\n\nPenggunaan: #play judul lagu, id)
hanz.reply(from, mess.wait, id)
const serplay = body.slice(6)
axios.get(https://api.vhtear.com/ytmp3?query=${serplay}&apikey=${vhtearkey})
.then(async(res) => {
if (Number(res.data.result.size.split(' MB')[0]) >= 10.00) return hanz.reply(from, 'Maaf durasi music sudah melebihi batas maksimal 10 MB!', id)
const saveit = await fetch(res.data.result.mp3)
const bufferlah = await saveit.buffer();
await sleep(1000)
fs.writeFile('./media/play.mp3', bufferlah)
await tobz.sendFile(from, './media/play.mp3, '', '', id)
})
break
