### ISSUE TITLE
Api Vhtear nya limit ya?

### ISSUE THREAD

**Issue by Rmdhn-20** [Urbaeexyz/whatsapp-bot2#24]
https://api.vhtear.com/hartatahta?text=exzuka&apikey=dicurimulu

**403 - APIKEY NOT FOUND**
Akses APIKEY tidak di izinkan - APIKEY access is not permitted.

**Comment by Urbaeexyz** [comment]
pake apikey sndiri

**Comment by Rmdhn-20** [comment]
huft:(
