### ISSUE TITLE
ERROR HELP!!!

### ISSUE THREAD

**Issue by Rmdhn-20** [Urbaeexyz/whatsapp-bot2#28]
![Screenshot (5)](https://user-images.githubusercontent.com/76412415/110367953-f0d83a00-807a-11eb-8fc8-af43abce6adf.png)

Tolong dong bang ini knpa ya??

**Comment by Urbaeexyz** [comment]
> ![Screenshot (5)](https://user-images.githubusercontent.com/76412415/110367953-f0d83a00-807a-11eb-8fc8-af43abce6adf.png)
> 
> Tolong dong bang ini knpa ya??

pake repo gw yang baru aja

https://github.com/Urbaeexyz/wa-bot

**Comment by Rmdhn-20** [comment]
Langsung star tuh bang😁
